version: '3'
services:
  pixelflut:
    restart: unless-stopped
    image: sbernauer/breakwater
    # build: .
    network_mode: host # Used ports are 1234, 5900 and 9100. Choosing host mode here for best performance

  node_exporter:
    restart: unless-stopped
    image: quay.io/prometheus/node-exporter:latest
    network_mode: host # Used ports are 9101
    pid: host
    volumes:
      - "/:/host:ro,rslave"
    command:
      - "--path.rootfs=/host"
      - "--web.listen-address=:9101"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:v2.32.1
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus-data:/prometheus"
    ports:
      - 9090:9090
    extra_hosts:
      - "pixelflut:172.17.0.1"

  grafana:
    restart: unless-stopped
    image: grafana/grafana:8.3.4
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning/"
      - "grafana-data:/var/lib/grafana"
    ports:
      - 80:3000
    extra_hosts:
      - "pixelflut:172.17.0.1"

volumes:
  grafana-data:
  prometheus-data:
