{
 "title": "Pixelflut overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Connected IPs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "breakwater_ips" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(breakwater_connections)" }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(breakwater_bytes[1m]))*8"
    }
   ]
  },
  {
   "title": "Total Traffic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(breakwater_bytes)" }
   ]
  },
  {
   "title": "FPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "breakwater_fps" }
   ]
  },
  {
   "title": "Connected IPs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "breakwater_ips", "legendFormat": "IPs" },
    { "expr": "breakwater_legacy_ips", "legendFormat": "Legacy IPs" }
   ]
  },
  {
   "title": "Traffic / IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "rate(breakwater_bytes[1m]) * 8", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "Connections / IP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "breakwater_connections", "legendFormat": "{{ip}}" }
   ]
  }
 ]
}